spring:
  data:
    redis:
      host: redis
      port: 6379

  application:
    name: RabbitMQ demo

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

  mail:
    host: fake-smtp
    port: 1025
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          starttls:
            enable: false
        debug: false

  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:mysql://mysql:3306/rabbitmq
    username: user
    password: password
